name: cd

on: 
  push:
    branches: [main]

jobs:
  deploys:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      DATABASE_URL : ${{ secrets.DATABASE_URL }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with: 
          go-version: '1.23.0'

      - name: Set up Goose
        uses: mscno/setup-goose@v1

      - name: Compile binary
        run: scripts/buildprod.sh

      - name: Auth
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Build Docker Image
        run: 'gcloud builds submit --tag europe-west3-docker.pkg.dev/notely-434215/notely-ar-repo/notely:latest .'

      - name: Run Migration with Goose
        run: ./scripts/migrateup.sh

      - name: Deploy to Cloud Run
        run: gcloud run deploy notely --image europe-west3-docker.pkg.dev/notely-434215/notely-ar-repo/notely:latest --region us-central1 --allow-unauthenticated --project notely-434215 --max-instances=4