name: cd

on: 
  push:
    branches: [main]

jobs:
  deploys:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with: 
          go-version: '1.23.0'

      - name: Compile binary
        run: scripts/buildprod.sh

      - name: Auth
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Deploy GCP
        run: 'gcloud builds submit --tag europe-west3-docker.pkg.dev/notely-434215/notely-ar-repo/notely:latest .'